import { readdirSync, readFileSync, statSync } from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

const rootDir = path.resolve(__dirname, '..');
const forbiddenTerms = ['igloo' + '-pa' + 'per', 'Pa' + 'per' + ' Desktop', 'design' + '-system'];
const scannedDirs = ['src', 'test', 'scripts'];
const scannedFiles = ['README.md', 'package.json'];

function collectTextFiles(dir: string): string[] {
  if (!statSync(dir, { throwIfNoEntry: false })?.isDirectory()) {
    return [];
  }

  const files: string[] = [];
  for (const entry of readdirSync(dir)) {
    const fullPath = path.join(dir, entry);
    const stat = statSync(fullPath);
    if (stat.isDirectory()) {
      if (entry !== 'node_modules' && entry !== 'dist') {
        files.push(...collectTextFiles(fullPath));
      }
      continue;
    }
    if (/\.(css|json|md|mjs|ts|tsx)$/.test(entry)) {
      files.push(fullPath);
    }
  }
  return files;
}

describe('design token handoff contract', () => {
  it('does not expose a package-level external sync command or generator', () => {
    const packageJson = JSON.parse(readFileSync(path.join(rootDir, 'package.json'), 'utf8'));

    expect(packageJson.scripts['sync:' + 'pa' + 'per' + '-tokens']).toBeUndefined();
  });

  it('keeps generated token outputs package-local and source-agnostic', () => {
    const css = readFileSync(path.join(rootDir, 'src', 'tokens', 'design-tokens.css'), 'utf8');
    const ts = readFileSync(path.join(rootDir, 'src', 'tokens', 'design-tokens.ts'), 'utf8');

    expect(css).toContain('Generated by frostr-infra token handoff.');
    for (const term of forbiddenTerms) {
      expect(css).not.toContain(term);
      expect(ts).not.toContain(term);
    }
  });

  it('does not reference parent workspace design repos or desktop design tooling', () => {
    const files = [
      ...scannedFiles.map((file) => path.join(rootDir, file)),
      ...scannedDirs.flatMap((dir) => collectTextFiles(path.join(rootDir, dir))),
    ];
    const offenders = files.flatMap((file) => {
      const text = readFileSync(file, 'utf8');
      return forbiddenTerms
        .filter((term) => text.includes(term))
        .map((term) => `${path.relative(rootDir, file)} contains ${term}`);
    });

    expect(offenders).toEqual([]);
  });
});
